import { Inter } from 'next/font/google';
import './globals.css';
import ScrollToTop from '@/components/scrolltotop';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Evil Wizards',
  description: 'Generated by Evil Magic',

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <link rel="icon" href="/skull.png" sizes="any" />
        <ScrollToTop />
        {children}
      </body>
    </html>
  );
}
