import { Inter } from 'next/font/google';
import './globals.css';
import ScrollToTop from '@/components/scrolltotop';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Evil Wizards',
  description: 'Generated by Evil Magic',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ScrollToTop />
        {children}
      </body>
    </html>
  );
}
